name = "project"
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
  id = "task1"
  title = ""
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "task2"
  title = ""
  description = ""
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process3"
name = "Done"
tasks = [
  { id = "task3", title = "Created MERN and MEAN projects.", description = "Completed setup and initial development for both MERN and MEAN projects.", tag = "completed", linkFiles = [ ], dueDate = "", checkList = [ ], priority = "high", linkCommits = [ ] }
]
